### ISSUE TITLE
本人整理了OWNER中文文档

### ISSUE THREAD

**Issue by cyfonly** [jobbole/awesome-java-cn#16]
你好，本人近段时间整理了 OWNER 的中文文档（已经和OWNER作者沟通过，往后OWNER的更新都将由本人同步整理）,详情请看本人github（ https://github.com/cyfonly/owner-doc ） 以及博客（ http://www.cnblogs.com/cyfonly/p/5523101.html ）  。希望对中文学习者有所帮助。

**Comment by tangyouhua** [comment]
你好，感谢贡献OWNER资源文档，
http://www.cnblogs.com/cyfonly/p/5523101.html 无法打开
https://github.com/cyfonly/owner-doc  已更新到 http://hao.jobbole.com/owner/ 的详细介绍中

**Comment by cyfonly** [comment]
hi, 感谢~~ 之前的地址无法打开的问题，已将地址更新为：http://www.cnblogs.com/cyfonly/p/5616489.html
