### ISSUE TITLE
javaweb框架推荐

### ISSUE THREAD

**Issue by heikehuan** [jobbole/awesome-java-cn#20]
这2个框架都是类似ssh的集成。都做了很多精简，适合快速开发。

**nutz**
官网：http://nutzam.com/
github: https://github.com/nutzam/nutz

**jfinal**
官网：http://www.jfinal.com/
osc: http://git.oschina.net/jfinal/jfinal

**Comment by tangyouhua** [comment]
感谢推荐:)
