### ISSUE TITLE
业务流程管理套件推荐---Activity

### ISSUE THREAD

**Issue by heikehuan** [jobbole/awesome-java-cn#21]
简介：在Java领域，JBPM和Activity是两个主流的工作流系统，而Activity的出现无疑将会取代JBPM（Activity的开发者就是从Jbpm开发者出来的）。

官网: http://www.activiti.org/
github:  https://github.com/Activiti/Activiti

**Comment by tangyouhua** [comment]
感谢推荐，已加入:)
