### ISSUE TITLE
java 的数据库连接池没有收录进来吗？

### ISSUE THREAD

**Issue by livem** [jobbole/awesome-java-cn#27]
java 的数据库连接池没有收录进来吗？

常用的例如：C3P0、Druid、HikariCP

**Comment by tangyouhua** [comment]
你好，Druid、HikariCP已收录，可以在大全里搜索。C3P0看了，目前star 500，可纳入观察。

**Comment by tangyouhua** [comment]
你好，Druid、HikariCP已收录，可以在大全里搜索。C3P0看了，目前star 500，可纳入观察。
感谢推荐:)

**Comment by livem** [comment]
druid 是指阿里巴巴开发的数据库连接池哦 https://github.com/alibaba/druid

还没进收录进来。

**Comment by tangyouhua** [comment]
好的呀，您直接PR吧
